import FormWrapper from './FormWrapper';
import FieldWrap from './FieldWrap';
import InputWrap from './InputWrap';

type UserData = {
    quickFireRedRhymeOne: string,
    quickFireRedClueOne: string,
    quickFireRedAnswerOne: string,
    quickFireRedRhymeTwo: string,
    quickFireRedClueTwo: string,
    quickFireRedAnswerTwo: string,
    quickFireRedRhymeThree: string,
    quickFireRedClueThree: string,
    quickFireRedAnswerThree: string,
    quickFireRedRhymeFour: string,
    quickFireRedClueFour: string,
    quickFireRedAnswerFour: string,
    quickFireRedRhymeFive: string,
    quickFireRedClueFive: string,
    quickFireRedAnswerFive: string,
    quickFireRedRhymeSix: string,
    quickFireRedClueSix: string,
    quickFireRedAnswerSix: string,
    quickFireRedRhymeSeven: string,
    quickFireRedClueSeven: string,
    quickFireRedAnswerSeven: string,
    quickFireRedRhymeEight: string,
    quickFireRedClueEight: string,
    quickFireRedAnswerEight: string,
    quickFireRedRhymeNine: string,
    quickFireRedClueNine: string,
    quickFireRedAnswerNine: string,
    quickFireRedRhymeTen: string,
    quickFireRedClueTen: string,
    quickFireRedAnswerTen: string,
    quickFireRedRhymeEleven: string,
    quickFireRedClueEleven: string,
    quickFireRedAnswerEleven: string,
    quickFireRedRhymeTwelve: string,
    quickFireRedClueTwelve: string,
    quickFireRedAnswerTwelve: string,
    quickFireRedRhymeThirteen: string,
    quickFireRedClueThirteen: string,
    quickFireRedAnswerThirteen: string,
    quickFireRedRhymeFourteen: string,
    quickFireRedClueFourteen: string,
    quickFireRedAnswerFourteen: string,
    quickFireRedRhymeFifteen: string,
    quickFireRedClueFifteen: string,
    quickFireRedAnswerFifteen: string,
    quickFireBlueRhymeOne: string,
    quickFireBlueClueOne: string,
    quickFireBlueAnswerOne: string,
    quickFireBlueRhymeTwo: string,
    quickFireBlueClueTwo: string,
    quickFireBlueAnswerTwo: string,
    quickFireBlueRhymeThree: string,
    quickFireBlueClueThree: string,
    quickFireBlueAnswerThree: string,
    quickFireBlueRhymeFour: string,
    quickFireBlueClueFour: string,
    quickFireBlueAnswerFour: string,
    quickFireBlueRhymeFive: string,
    quickFireBlueClueFive: string,
    quickFireBlueAnswerFive: string,
    quickFireBlueRhymeSix: string,
    quickFireBlueClueSix: string,
    quickFireBlueAnswerSix: string,
    quickFireBlueRhymeSeven: string,
    quickFireBlueClueSeven: string,
    quickFireBlueAnswerSeven: string,
    quickFireBlueRhymeEight: string,
    quickFireBlueClueEight: string,
    quickFireBlueAnswerEight: string,
    quickFireBlueRhymeNine: string,
    quickFireBlueClueNine: string,
    quickFireBlueAnswerNine: string,
    quickFireBlueRhymeTen: string,
    quickFireBlueClueTen: string,
    quickFireBlueAnswerTen: string,
    quickFireBlueRhymeEleven: string,
    quickFireBlueClueEleven: string,
    quickFireBlueAnswerEleven: string,
    quickFireBlueRhymeTwelve: string,
    quickFireBlueClueTwelve: string,
    quickFireBlueAnswerTwelve: string,
    quickFireBlueRhymeThirteen: string,
    quickFireBlueClueThirteen: string,
    quickFireBlueAnswerThirteen: string,
    quickFireBlueRhymeFourteen: string,
    quickFireBlueClueFourteen: string,
    quickFireBlueAnswerFourteen: string,
    quickFireBlueRhymeFifteen: string,
    quickFireBlueClueFifteen: string,
    quickFireBlueAnswerFifteen: string,
    team: boolean,
}

type UserFormProps = UserData & {
    updateFields: (fields: Partial<UserData>) => void
}

const QuickfireForm = (props: UserFormProps) => {
    const teamChoice = props.team;
    const isRedTeam = teamChoice === 'red';
    const {
        quickFireRedAnswerOne,
        quickFireRedRhymeOne,
        quickFireRedClueOne,
        quickFireRedAnswerTwo,
        quickFireRedRhymeTwo,
        quickFireRedClueTwo,
        quickFireRedAnswerThree,
        quickFireRedRhymeThree,
        quickFireRedClueThree,
        quickFireRedAnswerFour,
        quickFireRedRhymeFour,
        quickFireRedClueFour,
        quickFireRedAnswerFive,
        quickFireRedRhymeFive,
        quickFireRedClueFive,
        quickFireRedAnswerSix,
        quickFireRedRhymeSix,
        quickFireRedClueSix,
        quickFireRedAnswerSeven,
        quickFireRedRhymeSeven,
        quickFireRedClueSeven,
        quickFireRedAnswerEight,
        quickFireRedRhymeEight,
        quickFireRedClueEight,
        quickFireRedAnswerNine,
        quickFireRedRhymeNine,
        quickFireRedClueNine,
        quickFireRedAnswerTen,
        quickFireRedRhymeTen,
        quickFireRedClueTen,
        quickFireRedAnswerEleven,
        quickFireRedRhymeEleven,
        quickFireRedClueEleven,
        quickFireRedAnswerTwelve,
        quickFireRedRhymeTwelve,
        quickFireRedClueTwelve,
        quickFireRedAnswerThirteen,
        quickFireRedRhymeThirteen,
        quickFireRedClueThirteen,
        quickFireRedAnswerFourteen,
        quickFireRedRhymeFourteen,
        quickFireRedClueFourteen,
        quickFireRedAnswerFifteen,
        quickFireRedRhymeFifteen,
        quickFireRedClueFifteen,
        quickFireBlueAnswerOne,
        quickFireBlueRhymeOne,
        quickFireBlueClueOne,
        quickFireBlueAnswerTwo,
        quickFireBlueRhymeTwo,
        quickFireBlueClueTwo,
        quickFireBlueAnswerThree,
        quickFireBlueRhymeThree,
        quickFireBlueClueThree,
        quickFireBlueAnswerFour,
        quickFireBlueRhymeFour,
        quickFireBlueClueFour,
        quickFireBlueAnswerFive,
        quickFireBlueRhymeFive,
        quickFireBlueClueFive,
        quickFireBlueAnswerSix,
        quickFireBlueRhymeSix,
        quickFireBlueClueSix,
        quickFireBlueAnswerSeven,
        quickFireBlueRhymeSeven,
        quickFireBlueClueSeven,
        quickFireBlueAnswerEight,
        quickFireBlueRhymeEight,
        quickFireBlueClueEight,
        quickFireBlueAnswerNine,
        quickFireBlueRhymeNine,
        quickFireBlueClueNine,
        quickFireBlueAnswerTen,
        quickFireBlueRhymeTen,
        quickFireBlueClueTen,
        quickFireBlueAnswerEleven,
        quickFireBlueRhymeEleven,
        quickFireBlueClueEleven,
        quickFireBlueAnswerTwelve,
        quickFireBlueRhymeTwelve,
        quickFireBlueClueTwelve,
        quickFireBlueAnswerThirteen,
        quickFireBlueRhymeThirteen,
        quickFireBlueClueThirteen,
        quickFireBlueAnswerFourteen,
        quickFireBlueRhymeFourteen,
        quickFireBlueClueFourteen,
        quickFireBlueAnswerFifteen,
        quickFireBlueRhymeFifteen,
        quickFireBlueClueFifteen,
    } = props;

    const inputValues = [
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeOne' : 'quickFireBlueRhymeOne',
            rhymeValue: isRedTeam ? quickFireRedRhymeOne : quickFireBlueRhymeOne,
            rhymePlaceholder: isRedTeam ? 'Batshit' : 'Hippocratic oath',
            answerName: isRedTeam ? 'quickFireRedAnswerOne' : 'quickFireBlueAnswerOne',
            answerValue: isRedTeam ? quickFireRedAnswerOne : quickFireBlueAnswerOne,
            answerPlaceholder:  isRedTeam ? 'Pamphlet' : 'Indiana Jones',
            clueName: isRedTeam ? 'quickFireRedClueOne' : 'quickFireBlueClueOne',
            clueValue: isRedTeam ? quickFireRedClueOne : quickFireBlueClueOne,
            cluePlaceholder: isRedTeam ? 'A small booklet' : 'Film franchise',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeTwo' : 'quickFireBlueRhymeTwo',
            rhymeValue: isRedTeam ? quickFireRedRhymeTwo : quickFireBlueRhymeTwo,
            rhymePlaceholder: isRedTeam ? 'Lovebite' : 'What you laughing for?',
            answerName: isRedTeam ? 'quickFireRedAnswerTwo' : 'quickFireBlueAnswerTwo',
            answerValue: isRedTeam ? quickFireRedAnswerTwo : quickFireBlueAnswerTwo,
            answerPlaceholder: isRedTeam ? 'Bug\'s Life' : 'Half-past four',
            clueName: isRedTeam ? 'quickFireRedClueTwo' : 'quickFireBlueClueTwo',
            clueValue: isRedTeam ? quickFireRedClueTwo : quickFireBlueClueTwo,
            cluePlaceholder: isRedTeam ? 'A Pixar movie' : 'The time is',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeThree' : 'quickFireBlueRhymeThree',
            rhymeValue: isRedTeam ? quickFireRedRhymeThree : quickFireBlueRhymeThree,
            rhymePlaceholder: isRedTeam ? 'Burnt my pizza' : 'Sanitizer',
            answerName: isRedTeam ? 'quickFireRedAnswerThree' : 'quickFireBlueAnswerThree',
            answerValue: isRedTeam ? quickFireRedAnswerThree : quickFireBlueAnswerThree,
            answerPlaceholder: isRedTeam ? 'Burj Khalifa' : 'Danny Myers',
            clueName: isRedTeam ? 'quickFireRedClueThree' : 'quickFireBlueClueThree',
            clueValue: isRedTeam ? quickFireRedClueThree : quickFireBlueClueThree,
            cluePlaceholder: isRedTeam ? 'World\'s tallest skyscraper' : 'Frak\'s latest battle (Aug 2022)',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeFour' : 'quickFireBlueRhymeFour',
            rhymeValue: isRedTeam ? quickFireRedRhymeFour : quickFireBlueRhymeFour,
            rhymePlaceholder: isRedTeam ? 'Science professor' : 'Losing the plot',
            answerName: isRedTeam ? 'quickFireRedAnswerFour' : 'quickFireBlueAnswerFour',
            answerValue: isRedTeam ? quickFireRedAnswerFour : quickFireBlueAnswerFour,
            answerPlaceholder: isRedTeam ? 'Rhyming it fresher' : 'Glued to the spot',
            clueName: isRedTeam ? 'quickFireRedClueFour' : 'quickFireBlueClueFour',
            clueValue: isRedTeam ? quickFireRedClueFour : quickFireBlueClueFour,
            cluePlaceholder: isRedTeam ? 'A classic Pamphlet setup' : 'I can\'t move, I\'m',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeFive' : 'quickFireBlueRhymeFive',
            rhymeValue: isRedTeam ? quickFireRedRhymeFive : quickFireBlueRhymeFive,
            rhymePlaceholder: isRedTeam ? 'Youth hostel' : 'Now and again',
            answerName: isRedTeam ? 'quickFireRedAnswerFive' : 'quickFireBlueAnswerFive',
            answerValue: isRedTeam ? quickFireRedAnswerFive : quickFireBlueAnswerFive,
            answerPlaceholder: isRedTeam ? 'Bluebottle' : 'Fountains of Wayne',
            clueName: isRedTeam ? 'quickFireRedClueFive' : 'quickFireBlueClueFive',
            clueValue: isRedTeam ? quickFireRedClueFive : quickFireBlueClueFive,
            cluePlaceholder: isRedTeam ? 'A type of fly' : 'Stacey\'s Mom',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeSix' : 'quickFireBlueRhymeSix',
            rhymeValue: isRedTeam ? quickFireRedRhymeSix : quickFireBlueRhymeSix,
            rhymePlaceholder: isRedTeam ? 'Zigzag rope' : 'Backflip',
            answerName: isRedTeam ? 'quickFireRedAnswerSix' : 'quickFireBlueAnswerSix',
            answerValue: isRedTeam ? quickFireRedAnswerSix : quickFireBlueAnswerSix,
            answerPlaceholder: isRedTeam ? 'Tic tac toe' : 'RapGrid',
            clueName: isRedTeam ? 'quickFireRedClueSix' : 'quickFireBlueClueSix',
            clueValue: isRedTeam ? quickFireRedClueSix : quickFireBlueClueSix,
            cluePlaceholder: isRedTeam ? 'Noughts and crosses' : 'Set up by Drect',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeSeven' : 'quickFireBlueRhymeSeven',
            rhymeValue: isRedTeam ? quickFireRedRhymeSeven : quickFireBlueRhymeSeven,
            rhymePlaceholder: isRedTeam ? 'Scare you to death' : 'Get out of the car',
            answerName: isRedTeam ? 'quickFireRedAnswerSeven' : 'quickFireBlueAnswerSeven',
            answerValue: isRedTeam ? quickFireRedAnswerSeven : quickFireBlueAnswerSeven,
            answerPlaceholder: isRedTeam ? 'Mary Celeste' : 'Sound the alarm',
            clueName: isRedTeam ? 'quickFireRedClueSeven' : 'quickFireBlueClueSeven',
            clueValue: isRedTeam ? quickFireRedClueSeven : quickFireBlueClueSeven,
            cluePlaceholder: isRedTeam ? 'An abandoned ship' : 'Turn on the alert',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeEight' : 'quickFireBlueRhymeEight',
            rhymeValue: isRedTeam ? quickFireRedRhymeEight : quickFireBlueRhymeEight,
            rhymePlaceholder: isRedTeam ? 'Onion Bhaji' : 'Jamie Lannister',
            answerName: isRedTeam ? 'quickFireRedAnswerEight' : 'quickFireBlueAnswerEight',
            answerValue: isRedTeam ? quickFireRedAnswerEight : quickFireBlueAnswerEight,
            answerPlaceholder: isRedTeam ? 'Destruction Derby' : 'David Attenborough',
            clueName: isRedTeam ? 'quickFireRedClueEight' : 'quickFireBlueClueEight',
            clueValue: isRedTeam ? quickFireRedClueEight : quickFireBlueClueEight,
            cluePlaceholder: isRedTeam ? 'Racing video game' : 'Wildlife films',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeNine' : 'quickFireBlueRhymeNine',
            rhymeValue: isRedTeam ? quickFireRedRhymeNine : quickFireBlueRhymeNine,
            rhymePlaceholder: isRedTeam ? 'Ineffective' : 'When you\'re a praying mantis',
            answerName: isRedTeam ? 'quickFireRedAnswerNine' : 'quickFireBlueAnswerNine',
            answerValue: isRedTeam ? quickFireRedAnswerNine : quickFireBlueAnswerNine,
            answerPlaceholder: isRedTeam ? 'Jimi Hendrix' : 'Every day\'s a madness',
            clueName: isRedTeam ? 'quickFireRedClueNine' : 'quickFireBlueClueNine',
            clueValue: isRedTeam ? quickFireRedClueNine : quickFireBlueClueNine,
            cluePlaceholder: isRedTeam ? 'Musician' : 'Cruger lyric',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeTen' : 'quickFireBlueRhymeTen',
            rhymeValue: isRedTeam ? quickFireRedRhymeTen : quickFireBlueRhymeTen,
            rhymePlaceholder: isRedTeam ? 'What\s this? Scooby Do is not scared' : 'Overwhelm',
            answerName: isRedTeam ? 'quickFireRedAnswerTen' : 'quickFireBlueAnswerTen',
            answerValue: isRedTeam ? quickFireRedAnswerTen : quickFireBlueAnswerTen,
            answerPlaceholder: isRedTeam ? 'Wotsits, Hula Hoops and Pom-Bears' : 'Note to self',
            clueName: isRedTeam ? 'quickFireRedClueTen' : 'quickFireBlueClueTen',
            clueValue: isRedTeam ? quickFireRedClueTen : quickFireBlueClueTen,
            cluePlaceholder: isRedTeam ? 'Three bags of crisps' : 'I must remember that',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeEleven' : 'quickFireBlueRhymeEleven',
            rhymeValue: isRedTeam ? quickFireRedRhymeEleven : quickFireBlueRhymeEleven,
            rhymePlaceholder: isRedTeam ? 'Windsor Palace' : 'Domestic violence',
            answerName: isRedTeam ? 'quickFireRedAnswerEleven' : 'quickFireBlueAnswerEleven',
            answerValue: isRedTeam ? quickFireRedAnswerEleven : quickFireBlueAnswerEleven,
            answerPlaceholder: isRedTeam ? 'Rick Moranis' : 'Poetic license',
            clueName: isRedTeam ? 'quickFireRedClueEleven' : 'quickFireBlueClueEleven',
            clueValue: isRedTeam ? quickFireRedClueEleven : quickFireBlueClueEleven,
            cluePlaceholder: isRedTeam ? 'Song by Frak, and a celebrity' : 'Getting away with something because it rhymes',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeTwelve' : 'quickFireBlueRhymeTwelve',
            rhymeValue: isRedTeam ? quickFireRedRhymeTwelve : quickFireBlueRhymeTwelve,
            rhymePlaceholder: isRedTeam ? 'Sharing a room' : 'Empire',
            answerName: isRedTeam ? 'quickFireRedAnswerTwelve' : 'quickFireBlueAnswerTwelve',
            answerValue: isRedTeam ? quickFireRedAnswerTwelve : quickFireBlueAnswerTwelve,
            answerPlaceholder: isRedTeam ? 'Hair in my soup' : 'Headliner',
            clueName: isRedTeam ? 'quickFireRedClueTwelve' : 'quickFireBlueClueTwelve',
            clueValue: isRedTeam ? quickFireRedClueTwelve : quickFireBlueClueTwelve,
            cluePlaceholder: isRedTeam ? 'Umm waiter, there\'s a' : 'Something Cruger will never be',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeThirteen' : 'quickFireBlueRhymeThirteen',
            rhymeValue: isRedTeam ? quickFireRedRhymeThirteen : quickFireBlueRhymeThirteen,
            rhymePlaceholder: isRedTeam ? 'Tom Holland' : 'Seen and not heard',
            answerName: isRedTeam ? 'quickFireRedAnswerThirteen' : 'quickFireBlueAnswerThirteen',
            answerValue: isRedTeam ? quickFireRedAnswerThirteen : quickFireBlueAnswerThirteen,
            answerPlaceholder: isRedTeam ? 'Rock bottom' : 'Meeting Adjourned',
            clueName: isRedTeam ? 'quickFireRedClueThirteen' : 'quickFireBlueClueThirteen',
            clueValue: isRedTeam ? quickFireRedClueThirteen : quickFireBlueClueThirteen,
            cluePlaceholder: isRedTeam ? 'Lowest of the low' : 'What you say when a conference is over',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeFourteen' : 'quickFireBlueRhymeFourteen',
            rhymeValue: isRedTeam ? quickFireRedRhymeFourteen : quickFireBlueRhymeFourteen,
            rhymePlaceholder: isRedTeam ? 'Mum joke time' : 'Don\'t buy the great thighs of Kate Moss',
            answerName: isRedTeam ? 'quickFireRedAnswerFourteen' : 'quickFireBlueAnswerFourteen',
            answerValue: isRedTeam ? quickFireRedAnswerFourteen : quickFireBlueAnswerFourteen,
            answerPlaceholder: isRedTeam ? 'Umbro sign' : 'Ghost Rider, Snake Eyes, and Face Off',
            clueName: isRedTeam ? 'quickFireRedClueFourteen' : 'quickFireBlueClueFourteen',
            clueValue: isRedTeam ? quickFireRedClueFourteen : quickFireBlueClueFourteen,
            cluePlaceholder: isRedTeam ? 'Your mum\'s got a tattoo of the' : 'Three Nicholas Cage films',
        },
        {
            rhymeName: isRedTeam ? 'quickFireRedRhymeFifteen' : 'quickFireBlueRhymeFifteen',
            rhymeValue: isRedTeam ? quickFireRedRhymeFifteen : quickFireBlueRhymeFifteen,
            rhymePlaceholder: isRedTeam ? 'Wait patiently' : 'Rob Roy',
            answerName: isRedTeam ? 'quickFireRedAnswerFifteen' : 'quickFireBlueAnswerFifteen',
            answerValue: isRedTeam ? quickFireRedAnswerFifteen : quickFireBlueAnswerFifteen,
            answerPlaceholder: isRedTeam ? 'James Avery' : 'Top Boy',
            clueName: isRedTeam ? 'quickFireRedClueFifteen' : 'quickFireBlueClueFifteen',
            clueValue: isRedTeam ? quickFireRedClueFifteen : quickFireBlueClueFifteen,
            cluePlaceholder: isRedTeam ? 'Uncle Phil actor' : 'Netflix series',
        },
    ]

    return (
        <FormWrapper title="Quick Fire Rhymes">
            <p>Quick fire form - {teamChoice} team</p>
            <>
                { inputValues.map(inputVal => {
                    return (
                        <FieldWrap key={inputVal.answerName}>
                            <InputWrap label="Rhyme" inputName={inputVal.rhymeName} inputValue={inputVal.rhymeValue} updateFields={props.updateFields} placeholder={inputVal.rhymePlaceholder} data={props.data} />
                            <InputWrap label="Answer" inputName={inputVal.answerName} inputValue={inputVal.answerValue} updateFields={props.updateFields} placeholder={inputVal.answerPlaceholder} data={props.data} />
                            <InputWrap label="Clue" inputName={inputVal.clueName} inputValue={inputVal.clueValue} updateFields={props.updateFields} placeholder={`${inputVal.cluePlaceholder}...`} data={props.data} />
                        </FieldWrap>
                    )
                })}
            </>
        </FormWrapper>
    )
}

export default QuickfireForm;