import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Snowfall from 'react-snowfall'

import Overlay from '../components/UI/Overlay';
import Modal from '../components/UI/Modal';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Sounds Like</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Snowfall />
        <Overlay />
        <Modal>
            <h1>What does it sound like?</h1>
        </Modal>
      </main>
    </>
  )
}
