import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Snowfall from 'react-snowfall'

import Overlay from '../components/UI/Overlay';
import Modal from '../components/UI/Modal';

import Intro from '../components/sections/Intro';

const inter = Inter({ subsets: ['latin'] })
const snowFlakeSpeed = [0.25, 0.5];

export default function Home() {
  return (
    <>
      <Head>
        <title>Sounds Like</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Snowfall speed={snowFlakeSpeed} />
        <Overlay />
        <Modal>
            <Intro />
        </Modal>
      </main>
    </>
  )
}
